version: '3'

services:
  next:
    container_name: next
    image: node:17
    ports:
      - 3000:3000
    volumes:
      - ./next:/srv/app
    depends_on:
      - strapi
    working_dir: '/srv/app'
    command: 'npm run dev'

  strapi:
    container_name: strapi
    image: strapi/strapi
    environment:
      - NODE_ENV=develop
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=strapi
      - DATABASE_PASSWORD=strapi
    ports:
      - 1337:1337
    volumes:
      - ./app:/srv/app
    depends_on:
      - db
    command: 'strapi develop'

  db:
    container_name: postgres
    image: postgres
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_DB: strapi